name: fit_fusion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  numberpicker: ^2.1.2
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  wheel_slider: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pictures/

  fonts:
    - family: sairaStencilOne
      fonts:
        - asset: assets/fonts/SairaStencilOne-Regular.ttf
    - family: niramit
      fonts:
        - asset: assets/fonts/Niramit-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Niramit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Niramit-Bold.ttf
          weight: 900

