import 'package:fit_fusion/component.dart';
import 'package:flutter/material.dart';

class TermsAndConditions extends StatelessWidget {
  const TermsAndConditions({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: background,
        surfaceTintColor: background,
        leading: CIconButton(
          image: 'assets/icons/left.svg',
          onPressed: () => Navigator.pop(context),
          color: white,
        ),
      ),
      body: const Padding(
        padding: EdgeInsets.symmetric(horizontal: 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Heading
            Saira(text: "Terms and Conditions", size: 24),
            SizedBox(height: 10),
            Niramit(
              text: "This Application and our Services provide weight loss"
                  " management and information applications and content published over the"
                  " Internet and are intended only to assist users in their individual weight"
                  " loss effort. Venn Interactive, Inc is not a medical organization and our"
                  " staff cannot give you medical advice or diagnosis. Nothing contained in"
                  " this Website, the Applications or through the Services should be construed"
                  " as medical advice or diagnosis. The information and reports generated by us"
                  " should not be interpreted as a substitute for physician consultation,"
                  " evaluation, or treatment. You are urged and advised to seek the advice"
                  " of a physician before beginning any weight loss effort or regimen. This"
                  " Website, the Application and all related Services are intended for use only"
                  " by healthy adult individuals and are not intended for use by minors, pregnant"
                  " women, or individuals with any type of health condition. Such individuals are"
                  " specifically warned to seek professional medical advice prior to initiating"
                  " any form of weight loss effort or regimen. Health notices",
              weight: FontWeight.w500,
            ),
          ],
        ),
      ),
    );
  }
}
