// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVvT_cKqfW6zB5ryxhjrirAtEypL9uc18',
    appId: '1:1019494930871:web:e3e4c1cac064e7fdc67032',
    messagingSenderId: '1019494930871',
    projectId: 'fit-fusion-a70bf',
    authDomain: 'fit-fusion-a70bf.firebaseapp.com',
    storageBucket: 'fit-fusion-a70bf.appspot.com',
    measurementId: 'G-1LTE25BVVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZtxR92YZc0OWa7qoOV9MHmTG-6fqhag',
    appId: '1:1019494930871:android:40f217cc3920d3bcc67032',
    messagingSenderId: '1019494930871',
    projectId: 'fit-fusion-a70bf',
    storageBucket: 'fit-fusion-a70bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3g4T02S_xrWHavMglRnZddm8ZthgrWjU',
    appId: '1:1019494930871:ios:6f7da01a9c43cbbbc67032',
    messagingSenderId: '1019494930871',
    projectId: 'fit-fusion-a70bf',
    storageBucket: 'fit-fusion-a70bf.appspot.com',
    iosBundleId: 'com.example.fitFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3g4T02S_xrWHavMglRnZddm8ZthgrWjU',
    appId: '1:1019494930871:ios:6f7da01a9c43cbbbc67032',
    messagingSenderId: '1019494930871',
    projectId: 'fit-fusion-a70bf',
    storageBucket: 'fit-fusion-a70bf.appspot.com',
    iosBundleId: 'com.example.fitFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVvT_cKqfW6zB5ryxhjrirAtEypL9uc18',
    appId: '1:1019494930871:web:b0a9e8dd26031751c67032',
    messagingSenderId: '1019494930871',
    projectId: 'fit-fusion-a70bf',
    authDomain: 'fit-fusion-a70bf.firebaseapp.com',
    storageBucket: 'fit-fusion-a70bf.appspot.com',
    measurementId: 'G-BE7HVZKYQ3',
  );
}
