// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADvhClG7zL-tr5e621YfDQDkvRWNBvHQQ',
    appId: '1:464033418233:web:6b2cc87c258585b8340b28',
    messagingSenderId: '464033418233',
    projectId: 'fit-fusion-d02c8',
    authDomain: 'fit-fusion-d02c8.firebaseapp.com',
    storageBucket: 'fit-fusion-d02c8.appspot.com',
    measurementId: 'G-PQYW95BSGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZobTC5KhCjVGtSxEBdQKoMlhV77gvjo',
    appId: '1:464033418233:android:35ccafd8f736e490340b28',
    messagingSenderId: '464033418233',
    projectId: 'fit-fusion-d02c8',
    storageBucket: 'fit-fusion-d02c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Bbla1l4X5T8M-SJ8TVVcHWGD5DZQ_U',
    appId: '1:464033418233:ios:79440b706108c1fb340b28',
    messagingSenderId: '464033418233',
    projectId: 'fit-fusion-d02c8',
    storageBucket: 'fit-fusion-d02c8.appspot.com',
    iosBundleId: 'com.example.fitFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Bbla1l4X5T8M-SJ8TVVcHWGD5DZQ_U',
    appId: '1:464033418233:ios:79440b706108c1fb340b28',
    messagingSenderId: '464033418233',
    projectId: 'fit-fusion-d02c8',
    storageBucket: 'fit-fusion-d02c8.appspot.com',
    iosBundleId: 'com.example.fitFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvhClG7zL-tr5e621YfDQDkvRWNBvHQQ',
    appId: '1:464033418233:web:dcf974c07d007c86340b28',
    messagingSenderId: '464033418233',
    projectId: 'fit-fusion-d02c8',
    authDomain: 'fit-fusion-d02c8.firebaseapp.com',
    storageBucket: 'fit-fusion-d02c8.appspot.com',
    measurementId: 'G-M9NGGR822X',
  );
}
